[package]
name = "step_3_6"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
url = { version = "2.5.0", features = [ "serde" ] }
chrono = { features=["serde"], version = "0.4.34" }
serde = "1"
serde_yaml = "0.9.32"
toml = "0.4.2"
serde_json = "1.0.114"
