identifier = { ('a'..'z' | 'A'..'Z') ~ ('a'..'z' | 'Z'..'Z' | '0'..'9')* }
integer  = { ('0'..'9')* }
argument = { identifier | integer }


fill = { (ANY)? }
align = { "<" | "^" | ">" }
sign = { "+" | "-" }
width = { count }
precision = { "*" | count }
type = { "?" | "x?" | "X?" | identifier | "" }
count = { parameter | integer }
parameter = { "$" ~ argument }

format_spec = { ( fill? ~ align )? ~ sign? ~ "#"? ~ "0"? ~ width ~ ( "." ~ precision )? ~ type }

