[package]
name = "step_3_7"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
rand="*"
argon2="*"
sha3 = "0.10.8"
base64ct = "1.6.0"
uuid={ version = "1.7.0", features=["v4"]}