[package]
name = "step_3"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
clap = { version = "4.5.1", features = [ "derive" ] }
config = "0.14.0"
log = "0.4.21"
num_cpus = "1.16.0"
serde = "1.0.197"
url = { version = "2", features = ["serde"] }
crossbeam-channel = "0.5"

