[package]
name = "step_3_11"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
tokio={version="*", features=["full"]}
reqwest={version="*", features=["gzip"]}
clap={version="*", features=["derive"]}