[package]
name = "step_3_11"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
tokio = { version = "1.36" , features = [ "full" ] }
reqwest = { version = "0.11", features = [ "gzip" ] }
clap = { version = "4", features = [ "derive" ]}
num_cpus = "1.16.0"